


####
POST http://localhost:3333/api/auth/login HTTP/2.0
content-type: application/json

{
   "email": "willianleman@gmail.com",
   "password": "pass123"
}

####
GET http://localhost:3333/api/users HTTP/2.0
content-type: application/json

{
   "email": "willianleman@gmail.com",
   "password": "pass123"
}



#### 
POST http://localhost:3333/api/auth/register HTTP/1.1
content-type: application/json

{
    
    "name": "Willian Leman",
    "email": "willianleman@gmail.com",
    "password": "123"
}